/**
 * Code.gs - GENERATED single-file bundle of all src/*.gs.
 * For the no-terminal install: paste this whole file into one script file at
 * script.google.com. src/ is the source of truth - regenerate with
 * `bash tools/bundle.sh` after any change. Do not edit this file by hand.
 */

// ======================================================================
// Config.gs
// ======================================================================

/**
 * Config.gs - central configuration and Script Properties access.
 *
 * Secrets and per-install IDs live in Script Properties
 * (Apps Script editor: Project Settings > Script Properties), never in source.
 * Tunable knobs live in the "Config" sheet tab and can be edited without a redeploy.
 */
const Config = {
  // --- Script Property keys ---
  KEYS: {
    GEMINI_API_KEY: 'GEMINI_API_KEY',
    GEMINI_MODEL: 'GEMINI_MODEL',
    ADZUNA_APP_ID: 'ADZUNA_APP_ID',
    ADZUNA_APP_KEY: 'ADZUNA_APP_KEY',
    RAPIDAPI_KEY: 'RAPIDAPI_KEY',
    SHEET_ID: 'SHEET_ID',
    DRIVE_FOLDER_ID: 'DRIVE_FOLDER_ID',
    MASTER_CV_DOC_ID: 'MASTER_CV_DOC_ID',
    CANDIDATE_JSON: 'CANDIDATE_JSON'
  },

  props_() {
    return PropertiesService.getScriptProperties();
  },

  get(key, fallback) {
    const v = this.props_().getProperty(key);
    if (v === null || v === undefined) return fallback === undefined ? null : fallback;
    return v;
  },

  set(key, value) {
    this.props_().setProperty(key, String(value));
  },

  require(key) {
    const v = this.get(key);
    if (!v) throw new Error('Missing Script Property: ' + key + ' (set it in Project Settings > Script Properties).');
    return v;
  },

  // --- Safe defaults; override any of these via the "Config" sheet tab ---
  defaults: {
    GEMINI_MODEL: 'gemini-2.5-flash',
    SCORE_THRESHOLD: 62,       // minimum fit score (0-100) to queue for approval
    DAILY_SOURCE_CAP: 120,     // max new jobs ingested per day
    DAILY_APPROVAL_N: 25,      // max items pushed to the Approvals queue per day
    CHUNK_SIZE: 8,             // items processed per trigger run (respects the 6-min cap)
    AGENCY_DRAFTS_PER_RUN: 8,  // agency intro drafts created per run
    FOLLOWUP_DAYS: [3, 7]
  },

  /**
   * Read a tunable from the "Config" sheet tab, falling back to defaults.
   * Kept string/number tolerant so the sheet can hold either.
   */
  tunable(key) {
    try {
      const rows = Crm.readAll(Crm.TABS.CONFIG);
      for (let i = 0; i < rows.length; i++) {
        if (rows[i].key === key && rows[i].value !== '' && rows[i].value !== null) {
          const n = Number(rows[i].value);
          return isNaN(n) ? rows[i].value : n;
        }
      }
    } catch (e) { /* sheet not ready yet - use default */ }
    return this.defaults[key];
  },

  // --- Candidate profile ---
  // EDIT THIS to yourself. The easiest, no-redeploy way is to paste a JSON version of the
  // object below into a Script Property named CANDIDATE_JSON (Project Settings > Script
  // Properties); if that property is set it wins and you can leave this default untouched.
  // The example below is a South-African customer-service jobseeker - swap in your details.
  candidate() {
    const raw = this.get(this.KEYS.CANDIDATE_JSON);
    if (raw) {
      try { return JSON.parse(raw); } catch (e) { Logger.log('Bad CANDIDATE_JSON: ' + e); }
    }
    return {
      name: 'Your Full Name',
      firstName: 'Your',
      email: 'you@example.com',
      phone: '+27 00 000 0000',
      location: 'City, Province, Country',
      linkedin: 'linkedin.com/in/your-handle',
      // --- Search targeting (kept as a working SA example; edit to your roles/regions) ---
      tracks: ['customer service', 'client support', 'contact centre', 'BPO', 'admin', 'office support'],
      geos: ['Johannesburg', 'Gauteng', 'South Africa', 'Remote'],
      remoteOk: true,
      internationalRemoteOk: true,
      salaryTargetNet: [0, 0], // net/month, currency of your country; INTERNAL ONLY - never printed on any output
      keywords: ['customer service', 'billing', 'account', 'retention', 'complaint resolution',
        'zendesk', 'hubspot', 'intercom', 'contact centre', 'call centre',
        'client support', 'administrative assistant', 'office administrator', 'data capture'],
      summary: 'One or two sentences describing who you are, your experience and the role you want. This feeds the fit-scoring and the tailored CV summary, so make it specific and factual.'
    };
  },

  /**
   * Public ATS job boards to poll. Add company board tokens here.
   * type: greenhouse | lever | ashby | workable ; slug: the board token in the URL.
   */
  atsBoards() {
    return [
      // { type: 'greenhouse', slug: 'examplecompany' },
      // { type: 'lever', slug: 'examplecompany' },
      // { type: 'ashby', slug: 'examplecompany' },
      // { type: 'workable', slug: 'examplecompany' }
    ];
  },

  // Adzuna country codes to search. za = South Africa; add 'gb' / 'us' for intl remote.
  adzunaCountries() {
    return ['za'];
  },

  // Adzuna "what" search terms, one request per term per country.
  adzunaQueries() {
    return ['customer service', 'call centre agent', 'client support', 'administrative assistant'];
  },

  // JSearch (RapidAPI) search terms, one request per term. " in South Africa"
  // is appended by the fetcher, so keep these role-only.
  jsearchQueries() {
    return this.adzunaQueries();
  },

  // JSearch freshness window: all | today | 3days | week | month.
  // 'week' keeps links fresh (and stays within the free-tier call budget).
  jsearchDatePosted() {
    return 'week';
  },

  // --- Ingest filters (set any of these from the Setup tab, or as Script Properties) ---

  // Job boards to hard-exclude, comma-separated in Script Property EXCLUDED_DOMAINS
  // (e.g. "careers24"). Matched case-insensitively against a job's source AND its
  // resolved URL, so it also catches boards hidden behind an Adzuna redirect.
  // Default: exclude nothing.
  excludedDomains() {
    const raw = this.get('EXCLUDED_DOMAINS');
    if (raw === null || raw === '') return [];
    return String(raw).split(',').map(function (s) { return s.trim().toLowerCase(); }).filter(Boolean);
  },

  // Allowed regions for the location filter (STRICT allow-list), comma-separated in
  // Script Property ALLOWED_REGIONS (e.g. "gauteng,johannesburg,cape town"). When set,
  // a job is kept only if it is remote OR its location matches one of these; jobs
  // located elsewhere, and jobs with no readable location, are dropped. Pair with
  // excludedRegions to carve out sub-areas. Default: EMPTY = no location restriction.
  allowedRegions() {
    const raw = this.get('ALLOWED_REGIONS');
    if (raw === null || raw === '') return [];
    return String(raw).split(',').map(function (s) { return s.trim().toLowerCase(); }).filter(Boolean);
  },

  // Regions to hard-exclude even if otherwise in range, comma-separated in Script
  // Property EXCLUDED_REGIONS (e.g. "pretoria,vaal"). Dropped unless the job is
  // remote. Default: EMPTY = exclude nothing.
  excludedRegions() {
    const raw = this.get('EXCLUDED_REGIONS');
    if (raw === null || raw === '') return [];
    return String(raw).split(',').map(function (s) { return s.trim().toLowerCase(); }).filter(Boolean);
  },

  // Keep remote jobs from anywhere. Script Property ALLOW_REMOTE ("false" to disable).
  // Default: true.
  allowRemote() {
    const raw = this.get('ALLOW_REMOTE');
    if (raw === null || raw === '') return true;
    return String(raw).toLowerCase() !== 'false' && String(raw) !== '0';
  },

  // Whether to tailor a CV + cover for portal-only roles (no contact email).
  // Script Property TAILOR_FOR_PORTALS ("false" = tailor email applications only).
  // Default: true (tailor for portals too).
  tailorForPortals() {
    const raw = this.get('TAILOR_FOR_PORTALS');
    if (raw === null || raw === '') return true;
    return String(raw).toLowerCase() !== 'false' && String(raw) !== '0';
  }
};


// ======================================================================
// Gemini.gs
// ======================================================================

/**
 * Gemini.gs - thin wrapper over the Gemini generateContent REST API.
 * Called from GAS via UrlFetchApp. The API key lives in Script Properties.
 */
const Gemini = {
  endpoint_(model) {
    return 'https://generativelanguage.googleapis.com/v1beta/models/' +
      encodeURIComponent(model) + ':generateContent';
  },

  /**
   * Generate text (or structured JSON) from a prompt.
   * opts: { json:boolean, schema:object, temperature:number, maxOutputTokens:number, system:string }
   * Returns a string, or (when opts.json) a parsed object.
   */
  generate(prompt, opts) {
    opts = opts || {};
    const key = Config.require(Config.KEYS.GEMINI_API_KEY);
    const model = Config.get(Config.KEYS.GEMINI_MODEL) || Config.defaults.GEMINI_MODEL;
    const url = this.endpoint_(model) + '?key=' + encodeURIComponent(key);

    const genConfig = {
      temperature: opts.temperature == null ? 0.3 : opts.temperature,
      maxOutputTokens: opts.maxOutputTokens || 2048,
      // Gemini 2.5+ models spend output budget on hidden "thinking" tokens,
      // which truncates short answers. Our tasks are classification / short
      // generation, so disable thinking by default. Override with opts.thinkingBudget.
      thinkingConfig: { thinkingBudget: opts.thinkingBudget == null ? 0 : opts.thinkingBudget }
    };
    if (opts.json) {
      genConfig.responseMimeType = 'application/json';
      if (opts.schema) genConfig.responseSchema = opts.schema;
    }

    const payload = {
      contents: [{ role: 'user', parts: [{ text: prompt }] }],
      generationConfig: genConfig
    };
    if (opts.system) payload.systemInstruction = { parts: [{ text: opts.system }] };

    const text = this.fetchWithRetry_(url, payload);
    if (opts.json) {
      try { return JSON.parse(text); }
      catch (e) { throw new Error('Gemini did not return valid JSON: ' + e + ' :: ' + String(text).slice(0, 300)); }
    }
    return text;
  },

  fetchWithRetry_(url, payload) {
    const options = {
      method: 'post',
      contentType: 'application/json',
      payload: JSON.stringify(payload),
      muteHttpExceptions: true
    };
    let lastErr = '';
    for (let attempt = 0; attempt < 4; attempt++) {
      const res = UrlFetchApp.fetch(url, options);
      const code = res.getResponseCode();
      const body = res.getContentText();
      if (code === 200) return this.extractText_(JSON.parse(body));
      lastErr = 'HTTP ' + code + ': ' + String(body).slice(0, 300);
      if (code === 429 || code >= 500) {
        Utilities.sleep(Math.pow(2, attempt) * 1000);
        continue;
      }
      break; // non-retryable
    }
    throw new Error('Gemini request failed: ' + lastErr);
  },

  extractText_(json) {
    const cand = json && json.candidates && json.candidates[0];
    if (!cand) {
      const fb = json && json.promptFeedback ? JSON.stringify(json.promptFeedback) : '';
      throw new Error('Gemini returned no candidates. ' + fb);
    }
    const parts = cand.content && cand.content.parts;
    if (!parts || !parts.length) throw new Error('Gemini candidate had no parts.');
    return parts.map(function (p) { return p.text || ''; }).join('');
  }
};


// ======================================================================
// Prompts.gs
// ======================================================================

/**
 * Prompts.gs - single source of truth for all Gemini prompt templates.
 * Runtime uses these (clasp only pushes src/), so edit prompts HERE.
 * Substitution: {{name}} tokens are replaced by render(name, vars).
 *
 * House rules baked into every prompt: UK English, no fabrication, no em/en
 * dashes, never invent metrics/employers/dates, never state salary.
 */
const Prompts = {
  render(name, vars) {
    let t = this.templates[name];
    if (!t) throw new Error('Unknown prompt: ' + name);
    const v = vars || {};
    Object.keys(v).forEach(function (k) { t = t.split('{{' + k + '}}').join(String(v[k])); });
    return t;
  },

  templates: {
    scoring: [
      'You are a senior recruiter screening a job for a candidate. Return ONLY JSON matching the schema.',
      'fit_score: 0-100, how likely this candidate is to get an interview for this job.',
      'track: one of customer-service, admin, real-estate, mining, other.',
      'rationale: one honest sentence.',
      'matched_keywords / missing_keywords: from the candidate keyword list vs the role.',
      'Weigh relevance to the candidate tracks, seniority match, location/remote fit, and realistic interview odds.',
      'Do not inflate scores. A generic or senior/irrelevant role should score low.',
      '',
      'CANDIDATE:',
      '{{candidate}}',
      '',
      'JOB:',
      '{{job}}'
    ].join('\n'),

    cv_tailor: [
      'Write a tailored professional-summary paragraph (2-3 sentences) for this candidate applying to this specific job.',
      'Use ONLY facts present in the candidate profile. Do not invent metrics, tools, employers or achievements.',
      'UK English. No em or en dashes. No salary. Confident but truthful. Return plain text only, no heading.',
      '',
      'CANDIDATE:',
      '{{candidate}}',
      '',
      'JOB:',
      '{{job}}'
    ].join('\n'),

    cover_letter: [
      'Write a short, warm, professional cover letter (about 160-200 words) for this candidate applying to this job.',
      'Ground every claim in the candidate profile - no fabrication of metrics, tools, employers or dates.',
      'Structure: brief opening naming the role, 1-2 short paragraphs on relevant strengths, a confident close.',
      'UK English. No em or en dashes. Do not mention salary. Sign off with the candidate name.',
      'Return plain text only.',
      '',
      'CANDIDATE:',
      '{{candidate}}',
      '',
      'JOB:',
      '{{job}}'
    ].join('\n'),

    outreach: [
      'Write a short, personable application/introduction email BODY (about 90-130 words) from this candidate.',
      'Purpose: apply for or express interest in the role, and note that a CV is attached.',
      'Ground every claim in the candidate profile - no fabrication. UK English. No em or en dashes. No salary.',
      'Friendly and professional, not pushy. End with a clear, low-pressure call to action and the candidate name.',
      'Return plain text only (no subject line, no markdown).',
      '',
      'CANDIDATE:',
      '{{candidate}}',
      '',
      'ROLE / RECIPIENT:',
      '{{job}}'
    ].join('\n'),

    followup: [
      'Write a short, polite follow-up email BODY (about 60-90 words) from this candidate,',
      'sent {{stage}} after applying for the role, gently checking on the status and reaffirming interest.',
      'Ground every claim in the candidate profile - no fabrication. UK English. No em or en dashes. No salary.',
      'Warm, brief, not pushy. End with the candidate name. Return plain text only.',
      '',
      'CANDIDATE:',
      '{{candidate}}',
      '',
      'ROLE:',
      '{{job}}'
    ].join('\n'),

    interview_prep: [
      'You are a senior interview coach. For this candidate and this specific company/role, produce a concise prep pack.',
      'Include: (1) a 3-line company/role brief, (2) 6 likely interview questions, (3) for each, a one-line angle grounded in the candidate profile, (4) a 2-line honest gap-handling note, (5) 3 questions the candidate should ask.',
      'UK English. No em or en dashes. No fabrication. No salary figures. Return plain text.',
      '',
      'CANDIDATE:',
      '{{candidate}}',
      '',
      'JOB:',
      '{{job}}'
    ].join('\n')
  }
};


// ======================================================================
// Crm.gs
// ======================================================================

/**
 * Crm.gs - the Google Sheet is the application CRM.
 * One tab per concern; this module owns the schema and all reads/writes.
 */
const Crm = {
  TABS: {
    OPPORTUNITIES: 'Opportunities',
    APPROVALS: 'Approvals',
    CONTACTS: 'Contacts',
    KPIS: 'KPIs',
    CONFIG: 'Config'
  },

  HEADERS: {
    Opportunities: ['id', 'source', 'company', 'role', 'location', 'mode', 'url', 'contact_email',
      'posted_date', 'fit_score', 'track', 'rationale', 'status', 'cv_pdf_url', 'cover_url',
      'outreach_draft_url', 'applied_date', 'response', 'interview_date', 'notes', 'created_at', 'updated_at'],
    Approvals: ['id', 'company', 'role', 'url', 'fit_score', 'track', 'rationale',
      'cv_pdf_url', 'cover_url', 'outreach_draft_url', 'channel', 'decision', 'edited_notes'],
    Contacts: ['id', 'name', 'email', 'type', 'company', 'focus', 'last_contacted', 'notes'],
    KPIs: ['week_start', 'sourced', 'scored', 'queued', 'approved', 'submitted', 'sent', 'responses', 'interviews', 'notes'],
    Config: ['key', 'value']
  },

  ss_() {
    return SpreadsheetApp.openById(Config.require(Config.KEYS.SHEET_ID));
  },

  sheet_(tab) {
    const ss = this.ss_();
    let sh = ss.getSheetByName(tab);
    if (!sh) sh = ss.insertSheet(tab);
    return sh;
  },

  ensureSchema() {
    const ss = this.ss_();
    const self = this;
    Object.keys(this.HEADERS).forEach(function (tab) {
      let sh = ss.getSheetByName(tab);
      if (!sh) sh = ss.insertSheet(tab);
      const headers = self.HEADERS[tab];
      const firstRow = sh.getRange(1, 1, 1, headers.length).getValues()[0];
      const empty = firstRow.every(function (c) { return c === '' || c === null; });
      if (empty) {
        sh.getRange(1, 1, 1, headers.length).setValues([headers]);
        sh.setFrozenRows(1);
        sh.getRange(1, 1, 1, headers.length).setFontWeight('bold');
      }
    });
    const def = ss.getSheetByName('Sheet1');
    if (def && ss.getSheets().length > 1) { try { ss.deleteSheet(def); } catch (e) { /* ignore */ } }
  },

  // 1-based column number for a header on a tab (0 if the header is unknown).
  colIndex(tab, header) {
    return this.HEADERS[tab].indexOf(header) + 1;
  },

  appendRow(tab, obj) {
    const headers = this.HEADERS[tab];
    const row = headers.map(function (h) { return obj[h] === undefined ? '' : obj[h]; });
    this.sheet_(tab).appendRow(row);
  },

  readAll(tab) {
    const sh = this.sheet_(tab);
    const last = sh.getLastRow();
    if (last < 2) return [];
    const headers = this.HEADERS[tab];
    const values = sh.getRange(2, 1, last - 1, headers.length).getValues();
    return values.map(function (r, i) {
      const o = { _row: i + 2 };
      headers.forEach(function (h, c) { o[h] = r[c]; });
      return o;
    });
  },

  updateRow(tab, rowNumber, obj) {
    const headers = this.HEADERS[tab];
    const sh = this.sheet_(tab);
    const current = sh.getRange(rowNumber, 1, 1, headers.length).getValues()[0];
    headers.forEach(function (h, c) { if (obj[h] !== undefined) current[c] = obj[h]; });
    sh.getRange(rowNumber, 1, 1, headers.length).setValues([current]);
  },

  findOpportunity(id) {
    const rows = this.readAll(this.TABS.OPPORTUNITIES);
    for (let i = 0; i < rows.length; i++) if (rows[i].id === id) return rows[i];
    return null;
  },

  existsOpportunity(id) {
    return this.findOpportunity(id) !== null;
  },

  listByStatus(status) {
    return this.readAll(this.TABS.OPPORTUNITIES).filter(function (o) { return o.status === status; });
  },

  setStatus(rowNumber, status) {
    this.updateRow(this.TABS.OPPORTUNITIES, rowNumber, { status: status, updated_at: new Date() });
  }
};


// ======================================================================
// Sources.gs
// ======================================================================

/**
 * Sources.gs - job ingestion from compliant sources.
 * JSearch (RapidAPI, aggregates Google for Jobs: Indeed/LinkedIn/Glassdoor/PNet)
 * + Adzuna (official API) + public ATS JSON feeds (Greenhouse/Lever/Ashby/Workable).
 * Official APIs only - no scraping. Dedup by a stable content hash.
 * Adzuna's redirect links are validated (followed) at ingest and dead ones
 * dropped; JSearch and ATS return direct links, so they are trusted for speed.
 */
const Sources = {
  ingest(cap) {
    cap = cap || Config.tunable('DAILY_SOURCE_CAP');
    const self = this;
    const t0 = Date.now();
    const found = [];
    try { Array.prototype.push.apply(found, this.fromJSearch_()); } catch (e) { Logger.log('JSearch: ' + e); }
    try { Array.prototype.push.apply(found, this.fromAdzuna()); } catch (e) { Logger.log('Adzuna: ' + e); }
    Config.atsBoards().forEach(function (b) {
      try { Array.prototype.push.apply(found, self.fromAts(b)); }
      catch (e) { Logger.log('ATS ' + b.type + '/' + b.slug + ': ' + e); }
    });

    // Read existing ids ONCE. Calling Crm.existsOpportunity per job re-read the
    // whole sheet each time (quadratic, and worse as the sheet grows) - that plus
    // validating every link is what blew past the 6-minute execution limit.
    const seen = {};
    Crm.readAll(Crm.TABS.OPPORTUNITIES).forEach(function (o) { if (o.id) seen[o.id] = true; });

    const deadline = t0 + 5 * 60 * 1000;   // stop before Apps Script's 6-min hard kill
    let added = 0, dead = 0, excluded = 0, offloc = 0, stopped = false;
    for (let i = 0; i < found.length && added < cap; i++) {
      if (Date.now() > deadline) { stopped = true; break; }
      const job = found[i];
      if (!job.id || seen[job.id]) continue;
      seen[job.id] = true;   // also dedups within this run

      // Adzuna hands out redirect links: resolve to the real employer URL (durable,
      // and exposes the true domain so the exclusion below can see it), and drop
      // any that resolve to a dead page. JSearch/ATS already return direct links.
      if (/^adzuna/.test(job.source)) {
        const r = self.resolveUrl_(job.url);
        job.url = r.url;
        if (!r.alive) { dead++; continue; }
      }

      // Best-effort application email from the posting text - turns a job into an
      // "email application" (tailored CV + Gmail draft) rather than a portal role.
      if (!job.contact_email && job.descr) job.contact_email = Outreach.harvestEmail_(job.descr);

      if (self.isExcluded_(job)) { excluded++; continue; }
      if (!self.locationOk_(job)) { offloc++; continue; }

      Crm.appendRow(Crm.TABS.OPPORTUNITIES, {
        id: job.id, source: job.source, company: job.company, role: job.role,
        location: job.location, mode: job.mode, url: job.url, contact_email: job.contact_email || '',
        posted_date: job.posted_date || '', status: 'sourced',
        created_at: new Date(), updated_at: new Date()
      });
      added++;
    }
    const skips = [];
    if (dead) skips.push(dead + ' dead-link');
    if (excluded) skips.push(excluded + ' excluded-board');
    if (offloc) skips.push(offloc + ' out-of-location');
    if (skips.length) Logger.log('ingest: skipped ' + skips.join(', ') + '.');
    if (stopped) Logger.log('ingest: stopped at time budget; next run continues with what is still fresh.');
    return added;
  },

  /**
   * Resolve a redirect URL (e.g. Adzuna's) to the final employer URL by following
   * Location headers manually, so we can store the direct link and see the true
   * domain. Returns { url, alive }. Fails open (alive:true) on transient errors.
   */
  resolveUrl_(url, maxHops) {
    if (!url) return { url: url, alive: false };
    maxHops = maxHops || 4;
    let cur = url;
    try {
      for (let h = 0; h < maxHops; h++) {
        const res = UrlFetchApp.fetch(cur, {
          followRedirects: false, muteHttpExceptions: true, validateHttpsCertificates: false
        });
        const code = res.getResponseCode();
        if (code >= 300 && code < 400) {
          const hdr = res.getAllHeaders();
          let loc = hdr['Location'] || hdr['location'];
          if (Array.isArray(loc)) loc = loc[0];
          if (!loc) return { url: cur, alive: true };
          if (!/^https?:\/\//i.test(loc)) {
            const base = cur.match(/^(https?:\/\/[^\/]+)/);
            loc = (base ? base[1] : '') + (loc.charAt(0) === '/' ? loc : '/' + loc);
          }
          cur = loc;
          continue;
        }
        if (code >= 400) return { url: cur, alive: false };
        return { url: cur, alive: true };            // 2xx - resolved
      }
      return { url: cur, alive: true };              // too many hops; treat as alive
    } catch (e) {
      Logger.log('resolveUrl_ (' + url + '): ' + e);
      return { url: cur, alive: true };              // fail open on transient blip
    }
  },

  // True if a job's board is on the exclusion list (checks source + resolved URL).
  isExcluded_(job) {
    const bl = Config.excludedDomains();
    if (!bl.length) return false;
    const hay = (String(job.source) + ' ' + String(job.url)).toLowerCase();
    for (let i = 0; i < bl.length; i++) if (hay.indexOf(bl[i]) !== -1) return true;
    return false;
  },

  isRemote_(job) {
    if (String(job.mode || '').toLowerCase() === 'remote') return true;
    return /\bremote\b|work from home|wfh/.test(String(job.location || '').toLowerCase());
  },

  // Location gate. Remote (globally) is always kept. Excluded areas are dropped even
  // if otherwise in range. A job with no readable location is kept (don't miss vague
  // opps). Otherwise, when an allow-list is set, keep only locations that match it.
  locationOk_(job) {
    if (Config.allowRemote() && this.isRemote_(job)) return true;   // remote anywhere

    const loc = String(job.location || '').trim().toLowerCase();

    const blocked = Config.excludedRegions();
    if (loc) for (let i = 0; i < blocked.length; i++) if (loc.indexOf(blocked[i]) !== -1) return false;

    const allowed = Config.allowedRegions();
    if (!allowed.length) return true;                          // no allow-list -> keep the rest
    if (!loc) return true;                                     // no readable location -> keep (don't miss)
    for (let j = 0; j < allowed.length; j++) if (loc.indexOf(allowed[j]) !== -1) return true;
    return false;                                              // located outside the range -> drop
  },

  /**
   * Follow a job URL and report whether it resolves to a live posting.
   * Treats HTTP >= 400 as dead, and Adzuna's "no longer available" landing
   * page as dead. Fails open (returns true) on network/timeout errors so a
   * transient blip does not silently drop a good job.
   */
  linkAlive_(url) {
    if (!url) return false;
    try {
      const res = UrlFetchApp.fetch(url, {
        followRedirects: true, muteHttpExceptions: true, validateHttpsCertificates: false
      });
      const code = res.getResponseCode();
      if (code >= 400) return false;
      const body = res.getContentText().slice(0, 4000).toLowerCase();
      if (/no longer available|job (has )?expired|position (has )?been filled|this job is no longer/.test(body)) return false;
      return true;
    } catch (e) {
      Logger.log('linkAlive_ (' + url + '): ' + e);
      return true;
    }
  },

  hashId_(source, company, role, url) {
    const raw = [source, company, role, url].join('|').toLowerCase();
    const bytes = Utilities.computeDigest(Utilities.DigestAlgorithm.MD5, raw);
    const hex = bytes.map(function (b) { return ('0' + (b & 0xff).toString(16)).slice(-2); }).join('');
    return source.split(':')[0] + '_' + hex.slice(0, 16);
  },

  getJson_(url) {
    const res = UrlFetchApp.fetch(url, { muteHttpExceptions: true });
    if (res.getResponseCode() !== 200) throw new Error('HTTP ' + res.getResponseCode());
    return JSON.parse(res.getContentText());
  },

  fromAdzuna() {
    const appId = Config.get(Config.KEYS.ADZUNA_APP_ID);
    const appKey = Config.get(Config.KEYS.ADZUNA_APP_KEY) || Config.get('ADZUNA_API_KEY');
    if (!appId || !appKey) { Logger.log('Adzuna keys not set; skipping.'); return []; }
    const self = this;
    const out = [];
    Config.adzunaCountries().forEach(function (country) {
      Config.adzunaQueries().forEach(function (what) {
        const url = 'https://api.adzuna.com/v1/api/jobs/' + country + '/search/1' +
          '?app_id=' + encodeURIComponent(appId) +
          '&app_key=' + encodeURIComponent(appKey) +
          '&results_per_page=25' +
          '&what=' + encodeURIComponent(what) +
          '&sort_by=date' +          // newest first, so redirects are less likely expired
          '&max_days_old=10' +       // tighter window - stale postings 404 on click
          '&content-type=application/json';
        const res = UrlFetchApp.fetch(url, { muteHttpExceptions: true });
        if (res.getResponseCode() !== 200) { Logger.log('Adzuna ' + country + '/' + what + ' HTTP ' + res.getResponseCode()); return; }
        const data = JSON.parse(res.getContentText());
        (data.results || []).forEach(function (r) {
          const company = (r.company && r.company.display_name) || 'Unknown';
          const role = r.title || '';
          const jurl = r.redirect_url || '';
          const hay = (role + ' ' + (r.description || '')).toLowerCase();
          out.push({
            id: self.hashId_('adzuna:' + country, company, role, jurl),
            source: 'adzuna:' + country, company: company, role: role,
            location: (r.location && r.location.display_name) || '',
            mode: /remote|work from home|wfh/.test(hay) ? 'remote' : '',
            url: jurl, posted_date: r.created || '', descr: r.description || ''
          });
        });
      });
    });
    return out;
  },

  /**
   * JSearch (RapidAPI) - aggregates Google for Jobs, so one call covers
   * Indeed, LinkedIn, Glassdoor and SA boards (incl. PNet-sourced listings).
   * Returns DIRECT apply links (job_apply_link), so links are live by design.
   */
  fromJSearch_() {
    const key = Config.get(Config.KEYS.RAPIDAPI_KEY);
    if (!key) { Logger.log('JSearch key (RAPIDAPI_KEY) not set; skipping.'); return []; }
    const self = this;
    const out = [];
    const datePosted = Config.jsearchDatePosted();
    Config.jsearchQueries().forEach(function (what) {
      // JSearch's /search was retired in favour of /search-v2 (cursor pagination -
      // no page/num_pages). Omitting the cursor returns the first page, which is all we need.
      const url = 'https://jsearch.p.rapidapi.com/search-v2' +
        '?query=' + encodeURIComponent(what + ' in South Africa') +
        '&country=za' +
        '&date_posted=' + encodeURIComponent(datePosted);
      const res = UrlFetchApp.fetch(url, {
        method: 'get',
        muteHttpExceptions: true,
        headers: { 'X-RapidAPI-Key': key, 'X-RapidAPI-Host': 'jsearch.p.rapidapi.com' }
      });
      if (res.getResponseCode() !== 200) {
        Logger.log('JSearch "' + what + '" HTTP ' + res.getResponseCode() + ': ' + res.getContentText().slice(0, 200));
        return;
      }
      const data = JSON.parse(res.getContentText());
      self.pickJobs_(data).forEach(function (j) {
        const company = j.employer_name || 'Unknown';
        const role = j.job_title || '';
        const jurl = j.job_apply_link || '';
        if (!jurl) return;
        const publisher = j.job_publisher || 'jsearch';
        const loc = [j.job_city, j.job_state, j.job_country].filter(Boolean).join(', ') || (j.job_location || '');
        out.push({
          id: self.hashId_('jsearch:' + publisher, company, role, jurl),
          source: 'jsearch:' + publisher, company: company, role: role,
          location: loc,
          mode: j.job_is_remote ? 'remote' : '',
          url: jurl, posted_date: j.job_posted_at_datetime_utc || '',
          descr: j.job_description || ''
        });
      });
    });
    return out;
  },

  /**
   * Find the jobs array in a JSearch response, tolerant of envelope changes.
   * /search returned { data: [...] }; /search-v2 (cursor) nests it, e.g.
   * { data: { jobs: [...], cursor } }. Returns [] if none of the shapes match.
   */
  pickJobs_(data) {
    if (!data) return [];
    if (Array.isArray(data)) return data;
    if (Array.isArray(data.data)) return data.data;
    if (data.data && Array.isArray(data.data.jobs)) return data.data.jobs;
    if (Array.isArray(data.jobs)) return data.jobs;
    if (Array.isArray(data.results)) return data.results;
    return [];
  },

  fromAts(board) {
    switch (board.type) {
      case 'greenhouse': return this.fromGreenhouse_(board.slug);
      case 'lever': return this.fromLever_(board.slug);
      case 'ashby': return this.fromAshby_(board.slug);
      case 'workable': return this.fromWorkable_(board.slug);
      default: return [];
    }
  },

  fromGreenhouse_(slug) {
    const self = this;
    const data = this.getJson_('https://boards-api.greenhouse.io/v1/boards/' + slug + '/jobs');
    return (data.jobs || []).map(function (j) {
      return {
        id: self.hashId_('greenhouse:' + slug, slug, j.title, j.absolute_url),
        source: 'greenhouse:' + slug, company: slug, role: j.title,
        location: (j.location && j.location.name) || '', mode: '',
        url: j.absolute_url, posted_date: j.updated_at || ''
      };
    });
  },

  fromLever_(slug) {
    const self = this;
    const data = this.getJson_('https://api.lever.co/v0/postings/' + slug + '?mode=json');
    return (data || []).map(function (j) {
      return {
        id: self.hashId_('lever:' + slug, slug, j.text, j.hostedUrl),
        source: 'lever:' + slug, company: slug, role: j.text,
        location: (j.categories && j.categories.location) || '',
        mode: (j.categories && j.categories.commitment) || '',
        url: j.hostedUrl, posted_date: j.createdAt || ''
      };
    });
  },

  fromAshby_(slug) {
    const self = this;
    const data = this.getJson_('https://api.ashbyhq.com/posting-api/job-board/' + slug + '?includeCompensation=false');
    return (data.jobs || []).map(function (j) {
      return {
        id: self.hashId_('ashby:' + slug, slug, j.title, j.jobUrl),
        source: 'ashby:' + slug, company: slug, role: j.title,
        location: j.location || '', mode: j.isRemote ? 'remote' : '',
        url: j.jobUrl, posted_date: j.publishedAt || ''
      };
    });
  },

  fromWorkable_(slug) {
    const self = this;
    const data = this.getJson_('https://apply.workable.com/api/v1/widget/accounts/' + slug + '?details=true');
    return (data.jobs || []).map(function (j) {
      const loc = j.location ? [j.location.city, j.location.country].filter(Boolean).join(', ') : '';
      const url = j.url || j.shortlink || '';
      return {
        id: self.hashId_('workable:' + slug, slug, j.title, url),
        source: 'workable:' + slug, company: slug, role: j.title,
        location: loc, mode: j.remote ? 'remote' : '',
        url: url, posted_date: j.published_on || ''
      };
    });
  }
};


// ======================================================================
// Match.gs
// ======================================================================

/**
 * Match.gs - Gemini-powered fit scoring, and routing to the Approvals queue.
 */
const Match = {
  SCHEMA: {
    type: 'object',
    properties: {
      fit_score: { type: 'integer' },
      track: { type: 'string' },
      rationale: { type: 'string' },
      matched_keywords: { type: 'array', items: { type: 'string' } },
      missing_keywords: { type: 'array', items: { type: 'string' } }
    },
    required: ['fit_score', 'track', 'rationale']
  },

  scoreOne(opp) {
    const prompt = Prompts.render('scoring', {
      candidate: JSON.stringify(Config.candidate()),
      job: JSON.stringify({ company: opp.company, role: opp.role, location: opp.location, mode: opp.mode, url: opp.url })
    });
    return Gemini.generate(prompt, { json: true, schema: this.SCHEMA, temperature: 0.2, maxOutputTokens: 700 });
  },

  scoreQueue(chunk) {
    chunk = chunk || Config.tunable('CHUNK_SIZE');
    const threshold = Number(Config.tunable('SCORE_THRESHOLD'));
    const pending = Crm.listByStatus('sourced').slice(0, chunk);
    const self = this;
    let scored = 0, queued = 0;
    pending.forEach(function (opp) {
      try {
        const r = self.scoreOne(opp);
        const pass = Number(r.fit_score) >= threshold;
        const status = pass ? 'queued_for_approval' : 'scored';
        Crm.updateRow(Crm.TABS.OPPORTUNITIES, opp._row, {
          fit_score: r.fit_score, track: r.track, rationale: r.rationale,
          status: status, updated_at: new Date()
        });
        scored++;
        if (pass) { self.pushToApprovals_(opp, r); queued++; }
      } catch (e) {
        Logger.log('score ' + opp.id + ': ' + e);
        Crm.updateRow(Crm.TABS.OPPORTUNITIES, opp._row, {
          status: 'scored', rationale: 'score error: ' + e, updated_at: new Date()
        });
      }
    });
    return { scored: scored, queued: queued };
  },

  pushToApprovals_(opp, r) {
    Crm.appendRow(Crm.TABS.APPROVALS, {
      id: opp.id, company: opp.company, role: opp.role, url: opp.url,
      fit_score: r.fit_score, track: r.track, rationale: r.rationale,
      channel: opp.contact_email ? 'email' : 'portal', decision: '', edited_notes: ''
    });
  }
};


// ======================================================================
// Tailor.gs
// ======================================================================

/**
 * Tailor.gs - per-role CV + cover letter generation.
 *
 * CV: copies the master CV Google Doc (which must contain a {{SUMMARY}} token),
 * replaces the token with a Gemini-tailored, truthful summary, exports an
 * ATS-clean PDF into the Drive folder. Cover letter: a fresh Doc -> PDF.
 */
const Tailor = {
  tailorCv(opp) {
    const masterId = Config.require(Config.KEYS.MASTER_CV_DOC_ID);
    const folder = this.folderForOpp_(opp);
    const cand = Config.candidate();

    const summary = Gemini.generate(Prompts.render('cv_tailor', {
      candidate: JSON.stringify(cand),
      job: JSON.stringify({ company: opp.company, role: opp.role })
    }), { temperature: 0.4, maxOutputTokens: 400 }).trim();

    const baseName = 'CV - ' + cand.firstName + ' - ' + this.safe_(opp.company) + ' - ' + this.safe_(opp.role);
    const copyFile = DriveApp.getFileById(masterId).makeCopy(baseName, folder);
    const doc = DocumentApp.openById(copyFile.getId());
    doc.getBody().replaceText('\\{\\{SUMMARY\\}\\}', summary);
    doc.saveAndClose();

    const pdf = folder.createFile(DriveApp.getFileById(copyFile.getId()).getAs('application/pdf')).setName(baseName + '.pdf');
    return { docUrl: copyFile.getUrl(), pdfUrl: pdf.getUrl(), pdfId: pdf.getId(), summary: summary };
  },

  coverLetter(opp) {
    const folder = this.folderForOpp_(opp);
    const cand = Config.candidate();

    const text = Gemini.generate(Prompts.render('cover_letter', {
      candidate: JSON.stringify(cand),
      job: JSON.stringify({ company: opp.company, role: opp.role, location: opp.location })
    }), { temperature: 0.5, maxOutputTokens: 700 }).trim();

    const name = 'Cover - ' + cand.firstName + ' - ' + this.safe_(opp.company) + ' - ' + this.safe_(opp.role);
    const doc = DocumentApp.create(name);
    doc.getBody().setText(text);
    doc.saveAndClose();
    const file = DriveApp.getFileById(doc.getId());
    file.moveTo(folder);
    const pdf = folder.createFile(file.getAs('application/pdf')).setName(name + '.pdf');
    return { docUrl: file.getUrl(), pdfUrl: pdf.getUrl(), pdfId: pdf.getId(), text: text };
  },

  // Get-or-create a per-role subfolder named by company (fallback to role,
  // then "Unsorted") so each application's files live together.
  folderForOpp_(opp) {
    const root = DriveApp.getFolderById(Config.require(Config.KEYS.DRIVE_FOLDER_ID));
    let base = String(opp.company || '').trim();
    if (!base || base.toLowerCase() === 'unknown') base = String(opp.role || '').trim();
    const name = this.safe_(base) || 'Unsorted';
    const existing = root.getFoldersByName(name);
    return existing.hasNext() ? existing.next() : root.createFolder(name);
  },

  safe_(s) {
    return String(s || '').replace(/[^\w \-]/g, '').replace(/\s+/g, ' ').trim().slice(0, 40);
  }
};


// ======================================================================
// Outreach.gs
// ======================================================================

/**
 * Outreach.gs - Gmail DRAFTS only. Nothing is ever auto-sent.
 * A human reviews each draft in Gmail and clicks send.
 *
 * Two paths:
 *  - draftFor(opp, assets): a personalised application email to a posting's contact.
 *  - draftAgencyOutreach(): intro emails to the curated recruitment-agency list.
 */
const Outreach = {
  draftFor(opp, assets) {
    const cand = Config.candidate();
    const to = opp.contact_email;
    if (!to) return null;

    const subject = 'Application: ' + opp.role + ' - ' + cand.name;
    const body = Gemini.generate(Prompts.render('outreach', {
      candidate: JSON.stringify(cand),
      job: JSON.stringify({ company: opp.company, role: opp.role })
    }), { temperature: 0.5, maxOutputTokens: 500 }).trim();

    const draft = GmailApp.createDraft(to, subject, body, {
      name: cand.name,
      attachments: (assets && assets.attachments) || []
    });
    return draft.getId();
  },

  draftAgencyOutreach(limit) {
    limit = limit || Config.tunable('AGENCY_DRAFTS_PER_RUN');
    const cand = Config.candidate();
    const agencies = Crm.readAll(Crm.TABS.CONTACTS).filter(function (c) {
      return c.type === 'agency' && c.email && !c.last_contacted;
    });
    let n = 0;
    agencies.slice(0, limit).forEach(function (a) {
      const body = Gemini.generate(Prompts.render('outreach', {
        candidate: JSON.stringify(cand),
        job: JSON.stringify({ company: a.name, role: 'Customer Service / Client Support / Admin - candidate introduction' })
      }), { temperature: 0.5, maxOutputTokens: 500 }).trim();
      GmailApp.createDraft(a.email, 'Candidate available - Customer Service / Client Support', body, { name: cand.name });
      Crm.updateRow(Crm.TABS.CONTACTS, a._row, { last_contacted: new Date() });
      n++;
    });
    return n;
  },

  // Draft a follow-up email (Gmail draft) for a sent application with no response yet.
  draftFollowUp(opp, stageLabel) {
    const cand = Config.candidate();
    if (!opp.contact_email) return null;
    const body = Gemini.generate(Prompts.render('followup', {
      stage: stageLabel,
      candidate: JSON.stringify(cand),
      job: JSON.stringify({ company: opp.company, role: opp.role })
    }), { temperature: 0.5, maxOutputTokens: 400 }).trim();
    const subject = 'Following up: ' + opp.role + ' - ' + cand.name;
    return GmailApp.createDraft(opp.contact_email, subject, body, { name: cand.name }).getId();
  },

  // Best-effort extraction of an application email from posting text.
  harvestEmail_(text) {
    const m = String(text || '').match(/[A-Za-z0-9._%+\-]+@[A-Za-z0-9.\-]+\.[A-Za-z]{2,}/);
    return m ? m[0] : '';
  }
};


// ======================================================================
// Digest.gs
// ======================================================================

/**
 * Digest.gs - morning email digest to the candidate.
 *
 * Sends ONLY if there are roles awaiting a decision in the Approvals tab
 * (decision column still blank). This is a self-notification to you, not
 * outreach in your name - employer emails still stay as human-approved drafts.
 */
function morningDigest() {
  Crm.ensureSchema();

  const pending = Crm.readAll(Crm.TABS.APPROVALS).filter(function (a) {
    return !String(a.decision || '').trim();
  });
  if (!pending.length) {
    Logger.log('morningDigest: nothing to review - no email sent.');
    return;
  }

  pending.sort(function (a, b) { return Number(b.fit_score) - Number(a.fit_score); });

  const cand = Config.candidate();
  const sheetUrl = SpreadsheetApp.openById(Config.require(Config.KEYS.SHEET_ID)).getUrl();
  const noun = pending.length === 1 ? 'role' : 'roles';

  const rows = pending.map(function (a) {
    return '<tr>' +
      '<td style="padding:6px 10px;border-bottom:1px solid #eee;"><b>' + htmlEscape_(a.fit_score) + '</b></td>' +
      '<td style="padding:6px 10px;border-bottom:1px solid #eee;">' + htmlEscape_(a.role) + '</td>' +
      '<td style="padding:6px 10px;border-bottom:1px solid #eee;">' + htmlEscape_(a.company) + '</td>' +
      '<td style="padding:6px 10px;border-bottom:1px solid #eee;">' + htmlEscape_(a.track) + '</td>' +
      '<td style="padding:6px 10px;border-bottom:1px solid #eee;">' + (a.url ? '<a href="' + htmlEscape_(a.url) + '">view</a>' : '') + '</td>' +
      '</tr>';
  }).join('');

  const html = '<div style="font-family:Arial,Helvetica,sans-serif;color:#333;">' +
    '<h2 style="margin:0 0 2px;">Good morning, ' + htmlEscape_(cand.firstName) + '</h2>' +
    '<p style="margin:0 0 12px;color:#555;">' + pending.length + ' new ' + noun + ' to review.</p>' +
    '<table style="border-collapse:collapse;font-size:14px;">' +
    '<tr>' +
    '<th align="left" style="padding:6px 10px;border-bottom:2px solid #ccc;">Fit</th>' +
    '<th align="left" style="padding:6px 10px;border-bottom:2px solid #ccc;">Role</th>' +
    '<th align="left" style="padding:6px 10px;border-bottom:2px solid #ccc;">Company</th>' +
    '<th align="left" style="padding:6px 10px;border-bottom:2px solid #ccc;">Track</th>' +
    '<th style="border-bottom:2px solid #ccc;"></th>' +
    '</tr>' + rows + '</table>' +
    '<p style="margin:16px 0;"><a href="' + htmlEscape_(sheetUrl) + '" style="background:#6b6b6b;color:#fff;padding:9px 16px;border-radius:4px;text-decoration:none;">Open the Approvals sheet</a></p>' +
    '<p style="font-size:12px;color:#888;">Type "Approve" in the decision column for the ones you want. Tailored CVs, cover letters and email drafts are then prepared automatically.</p>' +
    '</div>';

  const plain = 'Good morning ' + cand.firstName + '\n\n' + pending.length + ' new ' + noun + ' to review:\n' +
    pending.map(function (a) { return '  [' + a.fit_score + '] ' + a.role + ' @ ' + a.company + '  ' + (a.url || ''); }).join('\n') +
    '\n\nApprovals sheet: ' + sheetUrl;

  try {
    MailApp.sendEmail({
      to: cand.email,
      subject: 'Job digest: ' + pending.length + ' new ' + noun + ' to review',
      body: plain,
      htmlBody: html,
      name: 'Job-Hunt Autopilot'
    });
    Logger.log('morningDigest: sent ' + pending.length + ' item(s) to ' + cand.email);
  } catch (e) {
    // Almost always a missing send_mail authorisation - re-run the project
    // once from the editor and grant permissions, then re-install triggers.
    Logger.log('morningDigest: SEND FAILED (' + cand.email + '): ' + e);
    throw e;
  }
}

function htmlEscape_(s) {
  return String(s === undefined || s === null ? '' : s)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}


// ======================================================================
// InterviewPrep.gs
// ======================================================================

/**
 * InterviewPrep.gs - when a role reaches status "interview", generate a
 * tailored prep pack (company brief, likely questions + angles, gap-handling,
 * questions to ask) as a Google Doc in the Drive folder.
 */
const InterviewPrep = {
  generateFor(opp) {
    const folder = Tailor.folderForOpp_(opp);
    const cand = Config.candidate();

    const text = Gemini.generate(Prompts.render('interview_prep', {
      candidate: JSON.stringify(cand),
      job: JSON.stringify({ company: opp.company, role: opp.role, location: opp.location })
    }), { temperature: 0.4, maxOutputTokens: 1400 }).trim();

    const name = 'Interview Prep - ' + cand.firstName + ' - ' + Tailor.safe_(opp.company) + ' - ' + Tailor.safe_(opp.role);
    const doc = DocumentApp.create(name);
    doc.getBody().setText(text);
    doc.saveAndClose();
    const file = DriveApp.getFileById(doc.getId());
    file.moveTo(folder);
    return { docUrl: file.getUrl() };
  }
};


// ======================================================================
// Report.gs
// ======================================================================

/**
 * Report.gs - weekly KPI + funnel summary.
 * Appends (or refreshes) this week's row on the KPIs tab AND creates a Gmail
 * DRAFT to the script owner. Nothing auto-sends, per the Assisted guardrail.
 * KPI figures are running totals from the Opportunities/Approvals tabs, so the
 * KPIs tab reads as a week-over-week trend (one row per Monday).
 */
const Report = {
  sendWeekly() {
    const opps = Crm.readAll(Crm.TABS.OPPORTUNITIES);
    const apprs = Crm.readAll(Crm.TABS.APPROVALS);
    const count = function (s) { return opps.filter(function (o) { return o.status === s; }).length; };
    const withVal = function (f) { return opps.filter(function (o) { return String(o[f] || '').trim() !== ''; }).length; };

    const kpi = {
      sourced: opps.length,
      scored: opps.filter(function (o) { return String(o.fit_score || '').trim() !== '' && !isNaN(Number(o.fit_score)); }).length,
      queued: apprs.length,                                       // reached the review queue
      approved: apprs.filter(function (a) { return String(a.decision || '').trim().toLowerCase() === 'approve'; }).length,
      submitted: withVal('applied_date'),                         // you marked it sent/submitted
      sent: withVal('outreach_draft_url'),                        // an outreach draft was created
      responses: withVal('response'),
      interviews: opps.filter(function (o) {
        return String(o.interview_date || '').trim() !== '' || o.status === 'interview' || o.status === 'offer';
      }).length
    };

    this.writeKpiRow_(kpi);

    const lines = [
      'Job-Hunt - weekly summary',
      '',
      'Opportunities tracked: ' + kpi.sourced,
      'Queued for approval:   ' + count('queued_for_approval'),
      'Drafted (ready):       ' + count('drafted'),
      'Submitted / sent:      ' + (count('submitted') + count('sent')),
      'Responses:             ' + kpi.responses,
      'Interviews:            ' + kpi.interviews,
      '',
      'Full funnel is on the KPIs tab (one row per week).',
      'Target: 2-5 interviews/week.',
      kpi.interviews >= 2
        ? 'Status: on track.'
        : 'Status: below target - consider widening keywords/geo, adding ATS boards, or lowering SCORE_THRESHOLD in the Config tab.'
    ];

    const to = Session.getEffectiveUser().getEmail();
    GmailApp.createDraft(to, 'Job-Hunt - weekly summary', lines.join('\n'));
    Logger.log('weeklyReport: KPIs row written + draft created for ' + to);
  },

  // Write this week's funnel to the KPIs tab; refresh the row if one already
  // exists for this week's Monday, so re-running does not create duplicates.
  writeKpiRow_(kpi) {
    const week = Utilities.formatDate(this.mondayOf_(new Date()), Session.getScriptTimeZone(), 'yyyy-MM-dd');
    const row = {
      week_start: week, sourced: kpi.sourced, scored: kpi.scored, queued: kpi.queued,
      approved: kpi.approved, submitted: kpi.submitted, sent: kpi.sent,
      responses: kpi.responses, interviews: kpi.interviews, notes: 'auto weekly snapshot'
    };
    const existing = Crm.readAll(Crm.TABS.KPIS).filter(function (r) {
      const w = (r.week_start instanceof Date)
        ? Utilities.formatDate(r.week_start, Session.getScriptTimeZone(), 'yyyy-MM-dd')
        : String(r.week_start).slice(0, 10);
      return w === week;
    })[0];
    if (existing) Crm.updateRow(Crm.TABS.KPIS, existing._row, row);
    else Crm.appendRow(Crm.TABS.KPIS, row);
  },

  mondayOf_(d) {
    const day = d.getDay();                       // 0=Sun .. 6=Sat
    const back = (day === 0 ? -6 : 1 - day);      // days back to Monday
    return new Date(d.getFullYear(), d.getMonth(), d.getDate() + back);
  }
};


// ======================================================================
// Loop.gs
// ======================================================================

/**
 * Loop.gs - trigger entry points (global functions the scheduler calls).
 * Each is chunked to respect the 6-minute execution cap.
 */

function dailySource() {
  Crm.ensureSchema();
  const added = Sources.ingest(Config.tunable('DAILY_SOURCE_CAP'));
  Logger.log('dailySource: added ' + added + ' new opportunities');
}

function scoreQueue() {
  Crm.ensureSchema();
  const r = Match.scoreQueue(Config.tunable('CHUNK_SIZE'));
  Logger.log('scoreQueue: scored ' + r.scored + ', queued ' + r.queued);
}

/**
 * For each Approvals row a human marked "Approve", build the tailored CV + cover,
 * and (if the posting has a contact email) a Gmail draft with the CV attached.
 * Nothing is sent - the human sends from Gmail / submits portals manually.
 */
function prepApprovedBatch() {
  Crm.ensureSchema();
  const approvals = Crm.readAll(Crm.TABS.APPROVALS).filter(function (a) {
    return String(a.decision).trim().toLowerCase() === 'approve';
  });

  let done = 0;
  const cap = Config.tunable('CHUNK_SIZE');
  for (let i = 0; i < approvals.length && done < cap; i++) {
    const a = approvals[i];
    const opp = Crm.findOpportunity(a.id);
    if (!opp) continue;
    if (['drafted', 'submitted', 'sent'].indexOf(opp.status) !== -1) continue;

    // Portal-only roles (no contact email): tailor a CV + cover only if the
    // TAILOR_FOR_PORTALS setting is on. Otherwise flag for manual application.
    if (!opp.contact_email && !Config.tailorForPortals()) {
      Crm.updateRow(Crm.TABS.OPPORTUNITIES, opp._row, {
        status: 'drafted',
        notes: 'Portal role - apply manually via the job link (tailored docs skipped by setting).',
        updated_at: new Date()
      });
      done++;
      continue;
    }

    try {
      const cv = Tailor.tailorCv(opp);
      const cover = Tailor.coverLetter(opp);

      let outreachRef = '';
      let note = 'Ready. Submit via the job link.';
      if (opp.contact_email) {
        const cvBlob = DriveApp.getFileById(cv.pdfId).getBlob();
        const draftId = Outreach.draftFor(opp, { attachments: [cvBlob] });
        outreachRef = draftId ? ('gmail-draft:' + draftId) : '';
        note = 'Gmail draft created (review + send).';
      } else {
        note = 'Portal role - submit manually via the job link with the tailored CV + cover.';
      }

      Crm.updateRow(Crm.TABS.OPPORTUNITIES, opp._row, {
        cv_pdf_url: cv.pdfUrl, cover_url: cover.pdfUrl, outreach_draft_url: outreachRef,
        status: 'drafted', notes: note, updated_at: new Date()
      });
      done++;
    } catch (e) {
      Logger.log('prep ' + a.id + ': ' + e);
    }
  }
  Logger.log('prepApprovedBatch: prepared ' + done);
}

/**
 * Draft +3 / +7 day follow-ups (Gmail drafts) for sent applications that have
 * a contact email and no response yet. Markers in `notes` prevent duplicates.
 */
function followUps() {
  Crm.ensureSchema();
  const days = Config.defaults.FOLLOWUP_DAYS; // [3, 7]
  const now = new Date();
  const rows = Crm.readAll(Crm.TABS.OPPORTUNITIES).filter(function (o) {
    return (o.status === 'sent' || o.status === 'submitted') && o.contact_email && !o.response;
  });

  let n = 0;
  rows.forEach(function (o) {
    const applied = o.applied_date ? new Date(o.applied_date) : null;
    if (!applied || isNaN(applied.getTime())) return;
    const ageDays = (now - applied) / 86400000;
    const notes = String(o.notes || '');
    try {
      if (ageDays >= days[1] && notes.indexOf('[fu7]') === -1) {
        Outreach.draftFollowUp(o, 'a week');
        Crm.updateRow(Crm.TABS.OPPORTUNITIES, o._row, { notes: (notes + ' [fu7]').trim(), updated_at: now });
        n++;
      } else if (ageDays >= days[0] && notes.indexOf('[fu3]') === -1) {
        Outreach.draftFollowUp(o, 'a few days');
        Crm.updateRow(Crm.TABS.OPPORTUNITIES, o._row, { notes: (notes + ' [fu3]').trim(), updated_at: now });
        n++;
      }
    } catch (e) { Logger.log('followUp ' + o.id + ': ' + e); }
  });
  Logger.log('followUps: drafted ' + n + ' follow-up(s)');
}

/**
 * Generate an interview-prep pack for any role at status "interview" that
 * doesn't have one yet (a marker + link is written into `notes`).
 */
function prepInterviews() {
  Crm.ensureSchema();
  const rows = Crm.readAll(Crm.TABS.OPPORTUNITIES).filter(function (o) {
    return o.status === 'interview' && String(o.notes || '').indexOf('[prepped]') === -1;
  });
  let n = 0;
  const cap = Config.tunable('CHUNK_SIZE');
  for (let i = 0; i < rows.length && n < cap; i++) {
    const o = rows[i];
    try {
      const r = InterviewPrep.generateFor(o);
      Crm.updateRow(Crm.TABS.OPPORTUNITIES, o._row, {
        notes: (String(o.notes || '') + ' [prepped] ' + r.docUrl).trim(), updated_at: new Date()
      });
      n++;
    } catch (e) { Logger.log('prepInterviews ' + o.id + ': ' + e); }
  }
  Logger.log('prepInterviews: generated ' + n + ' prep pack(s)');
}

function weeklyReport() {
  Crm.ensureSchema();
  Report.sendWeekly();
}

// Draft agency intro emails (run manually or on a light schedule).
function draftAgencyOutreach() {
  Crm.ensureSchema();
  const n = Outreach.draftAgencyOutreach(Config.tunable('AGENCY_DRAFTS_PER_RUN'));
  Logger.log('draftAgencyOutreach: created ' + n + ' agency drafts');
}


// ======================================================================
// Triggers.gs
// ======================================================================

/**
 * Triggers.gs - install/remove the time-driven triggers (the "loop").
 * Run installTriggers() once after setup.
 */
function installTriggers() {
  removeTriggers();
  ScriptApp.newTrigger('dailySource').timeBased().everyDays(1).atHour(6).create();
  ScriptApp.newTrigger('scoreQueue').timeBased().everyHours(1).create();
  ScriptApp.newTrigger('prepApprovedBatch').timeBased().everyHours(2).create();
  ScriptApp.newTrigger('morningDigest').timeBased().everyDays(1).atHour(7).create();
  ScriptApp.newTrigger('followUps').timeBased().everyDays(1).atHour(8).create();
  ScriptApp.newTrigger('prepInterviews').timeBased().everyDays(1).atHour(9).create();
  ScriptApp.newTrigger('weeklyReport').timeBased().onWeekDay(ScriptApp.WeekDay.MONDAY).atHour(7).create();
  ScriptApp.newTrigger('pruneDeadLinks').timeBased().onWeekDay(ScriptApp.WeekDay.SUNDAY).atHour(5).create();
  // Auto-stamp applied_date when you pick sent/submitted in the status dropdown.
  ScriptApp.newTrigger('onSheetEdit').forSpreadsheet(Config.require(Config.KEYS.SHEET_ID)).onEdit().create();
  Logger.log('Triggers installed.');
}

function removeTriggers() {
  ScriptApp.getProjectTriggers().forEach(function (t) { ScriptApp.deleteTrigger(t); });
  Logger.log('Existing triggers removed.');
}


// ======================================================================
// SheetUi.gs
// ======================================================================

/**
 * SheetUi.gs - human-facing conveniences on the CRM sheet:
 *   - dropdowns for the columns you edit by hand (Opportunities.status, Approvals.decision)
 *   - auto-stamp Opportunities.applied_date the moment you pick "sent"/"submitted"
 *   - a "Readme" tab with a what-to-do-when reference
 *
 * Run applySheetUi() once (setupProject() also calls it). The auto-stamp needs
 * the installable onEdit trigger that installTriggers() creates.
 */

const STATUS_VALUES = ['sourced', 'scored', 'queued_for_approval', 'drafted',
  'submitted', 'sent', 'responded', 'interview', 'offer', 'rejected', 'dead_link'];
const DECISION_VALUES = ['Approve', 'Skip'];

function applySheetUi() {
  Crm.ensureSchema();
  applyDropdowns_();
  buildReadmeTab_();
  Logger.log('Sheet UI applied: status/decision dropdowns + Readme tab.');
}

function applyDropdowns_() {
  setColumnDropdown_(Crm.TABS.OPPORTUNITIES, 'status', STATUS_VALUES);
  setColumnDropdown_(Crm.TABS.APPROVALS, 'decision', DECISION_VALUES);
}

function setColumnDropdown_(tab, header, values) {
  const sh = Crm.sheet_(tab);
  const col = Crm.colIndex(tab, header);
  if (col < 1) return;
  const numRows = sh.getMaxRows() - 1;   // every row under the header
  if (numRows < 1) return;
  const rule = SpreadsheetApp.newDataValidation()
    .requireValueInList(values, true)
    .setAllowInvalid(true)               // never reject a value the code writes
    .build();
  sh.getRange(2, col, numRows, 1).setDataValidation(rule);
}

/**
 * Installable onEdit handler (see installTriggers). When you set an
 * Opportunities row's status to sent/submitted, fill applied_date with today
 * if it is still blank - so follow-ups have a date to count from.
 */
function onSheetEdit(e) {
  try {
    if (!e || !e.range) return;
    const sh = e.range.getSheet();
    if (sh.getName() === SETUP_TAB) { maybeSaveSetup_(e); return; }
    if (sh.getName() !== Crm.TABS.OPPORTUNITIES) return;
    if (e.range.getNumRows() !== 1 || e.range.getNumColumns() !== 1) return;
    if (e.range.getColumn() !== Crm.colIndex(Crm.TABS.OPPORTUNITIES, 'status')) return;

    const val = String(e.value || '').trim().toLowerCase();
    if (val !== 'sent' && val !== 'submitted') return;

    const row = e.range.getRow();
    if (row < 2) return;
    const cell = sh.getRange(row, Crm.colIndex(Crm.TABS.OPPORTUNITIES, 'applied_date'));
    if (String(cell.getValue()).trim() === '') cell.setValue(new Date());
  } catch (err) {
    Logger.log('onSheetEdit: ' + err);
  }
}

function buildReadmeTab_() {
  const ss = SpreadsheetApp.openById(Config.require(Config.KEYS.SHEET_ID));
  let sh = ss.getSheetByName('Readme');
  if (!sh) sh = ss.insertSheet('Readme');
  sh.clear();
  try { ss.setActiveSheet(sh); ss.moveActiveSheet(1); } catch (e) { /* ignore */ }

  const H = true, P = false;
  const rows = [
    ['Job-Hunt CRM - Quick Reference', H],
    ['', P],
    ['1. Every day (about 10 minutes)', H],
    ['Open the Approvals tab. For each row read the role, company, fit_score and rationale, and open the job link.', P],
    ['In the "decision" column pick Approve (or Skip) from the dropdown.', P],
    ['Within ~2 hours the system tailors a CV + cover letter (PDF in Drive) and, where the posting has an email, a Gmail draft with the CV attached.', P],
    ['', P],
    ['2. When a draft / CV is ready (Opportunities tab)', H],
    ['Review the Gmail draft, tweak it, and send. For portal-only roles, open the job link and submit manually using the tailored CV + cover from the Drive folder.', P],
    ['Then on that Opportunities row, set the "status" dropdown:', P],
    ['      sent = you emailed the application', P],
    ['      submitted = you applied through a portal', P],
    ['"applied_date" fills in with today automatically when you choose sent or submitted - you do not type it.', P],
    ['', P],
    ['3. Follow-ups (automatic)', H],
    ['3 and 7 days after applied_date, follow-up Gmail drafts are created for emailed applications with no reply yet. Review and send them.', P],
    ['Portal-only roles with no contact email are not followed up automatically - chase those yourself.', P],
    ['', P],
    ['4. When you hear back (Opportunities tab)', H],
    ['Put their reply in the "response" column and set "status" to responded.', P],
    ['If an interview is booked, set "status" to interview and fill in "interview_date". An interview-prep Google Doc is generated automatically (link appears in "notes").', P],
    ['Finally set "status" to offer or rejected.', P],
    ['', P],
    ['5. What the statuses mean', H],
    ['sourced / scored / queued_for_approval / drafted - set by the system automatically.', P],
    ['submitted / sent / responded / interview / offer / rejected - you set these by hand.', P],
    ['dead_link - the job link was dead, so it was skipped.', P],
    ['', P],
    ['6. The tabs', H],
    ['Opportunities - every job and its full history (the master record).', P],
    ['Approvals - your daily review queue; only pick Approve/Skip here.', P],
    ['Contacts - recruitment agencies.   Config / KPIs - system settings and stats.', P],
    ['', P],
    ['7. The automatic schedule (Johannesburg time)', H],
    ['06:00 pull new jobs   |   hourly score fit   |   every 2h prepare approved roles', P],
    ['07:00 morning digest email   |   08:00 follow-up drafts   |   09:00 interview prep   |   Mon 07:00 weekly report', P]
  ];

  sh.getRange(1, 1, rows.length, 1).setValues(rows.map(function (r) { return [r[0]]; }));
  sh.setColumnWidth(1, 780);
  sh.getRange(1, 1).setFontSize(14);
  rows.forEach(function (r, i) {
    if (r[1] === H) sh.getRange(i + 1, 1).setFontWeight('bold');
  });
  sh.setFrozenRows(1);
  try { sh.getRange(1, 1, rows.length, 1).setWrap(true); } catch (e) { /* ignore */ }
  try { sh.setHiddenGridlines(true); } catch (e) { /* ignore */ }
}


// ======================================================================
// Onboarding.gs
// ======================================================================

/**
 * Onboarding.gs - a no-code "answer the questions" setup form.
 *
 * It lives as a "Setup" tab in the CRM sheet. The candidate types their answers
 * in column B, then EITHER ticks the Save checkbox (works once installTriggers()
 * is on, via the installable onEdit trigger) OR runs applySetup() from the Run
 * menu. applySetup() writes the profile answers to the CANDIDATE_JSON Script
 * Property and each pasted API key to Script Properties, then blanks the secret
 * cells so keys do not linger in the sheet.
 *
 * seedSetupTab() is called by setupProject(); re-run it any time to refresh the
 * form (it preserves answers already typed).
 */

const SETUP_TAB = 'Setup';

// Ordered form definition.
// type: section | text | list | salary | prop | save | status
// target: candidate field (text/list/salary) or Script Property key (prop).
const SETUP_FIELDS = [
  { type: 'section', label: 'YOUR PROFILE  -  type answers in column B, then Save at the bottom' },
  { type: 'text',   label: 'Full name',                                             target: 'name' },
  { type: 'text',   label: 'Email (where your digests and outreach drafts go)',     target: 'email' },
  { type: 'text',   label: 'Phone',                                                 target: 'phone' },
  { type: 'text',   label: 'Location (City, Province, Country)',                     target: 'location' },
  { type: 'text',   label: 'LinkedIn URL',                                          target: 'linkedin' },
  { type: 'list',   label: 'Target roles (comma-separated)',                        target: 'tracks' },
  { type: 'list',   label: 'Regions / cities you will work in (comma-separated)',   target: 'geos' },
  { type: 'list',   label: 'Skill keywords (comma-separated)',                      target: 'keywords' },
  { type: 'salary', label: 'Salary target net per month, low and high (e.g. 15000, 20000) - private, never shown', target: 'salaryTargetNet' },
  { type: 'text',   label: 'One-line summary of you (feeds fit-scoring and your CV summary)', target: 'summary' },
  { type: 'section', label: 'API KEYS  -  paste each; on Save they move to secure storage and these cells are cleared' },
  { type: 'prop',   label: 'Gemini API key',                       target: 'GEMINI_API_KEY', secret: true },
  { type: 'prop',   label: 'Adzuna App ID',                        target: 'ADZUNA_APP_ID' },
  { type: 'prop',   label: 'Adzuna App Key',                       target: 'ADZUNA_APP_KEY', secret: true },
  { type: 'prop',   label: 'RapidAPI key (optional, for JSearch)', target: 'RAPIDAPI_KEY', secret: true },
  { type: 'prop',   label: 'Master CV Google Doc ID (the Doc that contains a {{SUMMARY}} token)', target: 'MASTER_CV_DOC_ID' },
  { type: 'section', label: 'SEARCH FILTERS  -  optional; leave blank to keep the defaults in brackets' },
  { type: 'prop',   label: 'Keep ONLY these regions, comma-separated (blank = anywhere)',              target: 'ALLOWED_REGIONS' },
  { type: 'prop',   label: 'Drop these sub-areas even if in range, comma-separated (blank = none)',    target: 'EXCLUDED_REGIONS' },
  { type: 'prop',   label: 'Allow remote jobs from anywhere? true/false (default true)',              target: 'ALLOW_REMOTE' },
  { type: 'prop',   label: 'Exclude these job boards, comma-separated e.g. careers24 (blank = none)', target: 'EXCLUDED_DOMAINS' },
  { type: 'prop',   label: 'Tailor CV/cover for portal roles too? true/false; false = email-only (default true)', target: 'TAILOR_FOR_PORTALS' },
  { type: 'section', label: 'SAVE' },
  { type: 'save',   label: 'Tick this box to save   (or run applySetup from the Run menu)' },
  { type: 'status', label: 'Status' }
];

function setupKey_(s) { return String(s).trim().toLowerCase(); }

/** Build (or refresh) the Setup tab, preserving any answers already typed. */
function seedSetupTab() {
  const ss = SpreadsheetApp.openById(Config.require(Config.KEYS.SHEET_ID));
  let sh = ss.getSheetByName(SETUP_TAB);
  if (!sh) sh = ss.insertSheet(SETUP_TAB);

  const prior = readSetupAnswers_(sh);   // keep what the user already typed
  const cand = Config.candidate();
  sh.clear();

  const rows = SETUP_FIELDS.map(function (f) {
    let b = '';
    const priorVal = prior[setupKey_(f.label)];
    if (f.type === 'text' || f.type === 'list' || f.type === 'salary') {
      b = (priorVal !== undefined && priorVal !== '') ? priorVal : candidateDisplay_(cand, f);
    } else if (f.type === 'prop') {
      b = (priorVal !== undefined) ? priorVal : '';   // never surface stored secrets
    }
    return [f.label, b];
  });

  sh.getRange(1, 1, rows.length, 2).setValues(rows);

  // Formatting
  sh.setColumnWidth(1, 420);
  sh.setColumnWidth(2, 460);
  sh.setFrozenColumns(1);
  SETUP_FIELDS.forEach(function (f, i) {
    const r = i + 1;
    if (f.type === 'section') {
      sh.getRange(r, 1, 1, 2).setFontWeight('bold').setBackground('#e8eaed');
    }
    if (f.type === 'status') sh.getRange(r, 1).setFontWeight('bold');
  });
  try { sh.getRange(1, 1, rows.length, 2).setWrap(true); } catch (e) { /* ignore */ }
  try { sh.setHiddenGridlines(true); } catch (e) { /* ignore */ }

  // Save checkbox
  const saveRow = rowOfType_('save');
  if (saveRow) sh.getRange(saveRow, 2).insertCheckboxes().setValue(false);

  try { ss.setActiveSheet(sh); ss.moveActiveSheet(1); } catch (e) { /* ignore */ }
  Logger.log('Setup tab ready. Fill it in, then tick Save (or run applySetup).');
}

/** Read the answers into the CANDIDATE_JSON property + Script Properties. */
function applySetup() {
  const ss = SpreadsheetApp.openById(Config.require(Config.KEYS.SHEET_ID));
  const sh = ss.getSheetByName(SETUP_TAB);
  if (!sh) throw new Error('No Setup tab yet - run setupProject() (or seedSetupTab()) first.');

  const ans = readSetupAnswers_(sh);
  const cand = Config.candidate();   // base = current profile (default or existing CANDIDATE_JSON)
  const keysSet = [];
  const clearRows = [];

  SETUP_FIELDS.forEach(function (f) {
    if (!f.target) return;
    const raw = ans[setupKey_(f.label)];
    if (raw === undefined) return;
    const v = String(raw).trim();
    if (f.type === 'text') {
      if (v) cand[f.target] = v;
    } else if (f.type === 'list') {
      if (v) cand[f.target] = v.split(',').map(function (s) { return s.trim(); }).filter(Boolean);
    } else if (f.type === 'salary') {
      if (v) {
        const nums = v.split(',')
          .map(function (s) { return Number(String(s).replace(/[^0-9.]/g, '')); })
          .filter(function (n) { return !isNaN(n) && n !== 0; });
        if (nums.length >= 2) cand[f.target] = [nums[0], nums[1]];
        else if (nums.length === 1) cand[f.target] = [nums[0], nums[0]];
      }
    } else if (f.type === 'prop') {
      if (v) {
        Config.set(f.target, v);
        keysSet.push(f.target);
        if (f.secret) clearRows.push(f.label);
      }
    }
  });

  // Derive firstName from name; keep the remote flags sensible.
  const nm = String(cand.name || '').trim();
  if (nm && nm !== 'Your Full Name') cand.firstName = nm.split(/\s+/)[0];
  if (cand.remoteOk === undefined) cand.remoteOk = true;
  if (cand.internationalRemoteOk === undefined) cand.internationalRemoteOk = true;

  Config.set(Config.KEYS.CANDIDATE_JSON, JSON.stringify(cand));

  // Clear saved secret cells + reset the Save checkbox.
  clearRows.forEach(function (label) {
    const r = rowOfLabel_(sh, label);
    if (r) sh.getRange(r, 2).setValue('');
  });
  const saveRow = rowOfType_('save');
  if (saveRow) { try { sh.getRange(saveRow, 2).setValue(false); } catch (e) { /* ignore */ } }

  const stamp = Utilities.formatDate(new Date(), Session.getScriptTimeZone(), 'yyyy-MM-dd HH:mm');
  const msg = 'Saved ' + stamp + '. Profile updated'
    + (keysSet.length ? '; keys stored: ' + keysSet.join(', ') : '')
    + (clearRows.length ? '; secret cells cleared.' : '.');
  const statusRow = rowOfType_('status');
  if (statusRow) sh.getRange(statusRow, 2).setValue(msg);
  Logger.log(msg);
  return msg;
}

/** Called from onSheetEdit when the Setup tab's Save checkbox is ticked. */
function maybeSaveSetup_(e) {
  try {
    const sh = e.range.getSheet();
    if (e.range.getNumRows() !== 1 || e.range.getNumColumns() !== 1) return;
    if (e.range.getColumn() !== 2) return;
    const label = String(sh.getRange(e.range.getRow(), 1).getValue() || '').trim();
    const saveField = SETUP_FIELDS.filter(function (f) { return f.type === 'save'; })[0];
    if (!saveField || setupKey_(label) !== setupKey_(saveField.label)) return;
    if (String(e.value).toLowerCase() === 'true') applySetup();
  } catch (err) {
    Logger.log('maybeSaveSetup_: ' + err);
  }
}

// --- helpers ---
function readSetupAnswers_(sh) {
  const out = {};
  const last = sh.getLastRow();
  if (last < 1) return out;
  const vals = sh.getRange(1, 1, last, 2).getValues();
  vals.forEach(function (r) {
    const label = String(r[0] || '').trim();
    if (label) out[setupKey_(label)] = r[1];
  });
  return out;
}

function candidateDisplay_(cand, f) {
  const val = cand[f.target];
  if (val === undefined || val === null) return '';
  if (Array.isArray(val)) return val.join(', ');
  return String(val);
}

function rowOfType_(type) {
  for (let i = 0; i < SETUP_FIELDS.length; i++) if (SETUP_FIELDS[i].type === type) return i + 1;
  return 0;
}

function rowOfLabel_(sh, label) {
  const last = sh.getLastRow();
  if (last < 1) return 0;
  const col = sh.getRange(1, 1, last, 1).getValues();
  for (let i = 0; i < col.length; i++) {
    if (setupKey_(col[i][0]) === setupKey_(label)) return i + 1;
  }
  return 0;
}


// ======================================================================
// Setup.gs
// ======================================================================

/**
 * Setup.gs - one-time bootstrap. Run setupProject() once, after:
 *   1. clasp push (this code is in the Apps Script project)
 *   2. GEMINI_API_KEY set in Script Properties
 * It creates the CRM spreadsheet + Drive folder, records their IDs, and seeds
 * the schema. Adzuna keys and MASTER_CV_DOC_ID can be added before or after.
 */
function setupProject() {
  // 1. CRM spreadsheet
  let sheetId = Config.get(Config.KEYS.SHEET_ID);
  if (!sheetId) {
    const ss = SpreadsheetApp.create('Job-Hunt CRM');
    sheetId = ss.getId();
    Config.set(Config.KEYS.SHEET_ID, sheetId);
    Logger.log('Created CRM sheet: ' + ss.getUrl());
  }

  // 2. Drive folder for tailored PDFs
  let folderId = Config.get(Config.KEYS.DRIVE_FOLDER_ID);
  if (!folderId) {
    const folder = DriveApp.createFolder('Job-Hunt - Tailored CVs & Covers');
    folderId = folder.getId();
    Config.set(Config.KEYS.DRIVE_FOLDER_ID, folderId);
    Logger.log('Created Drive folder: ' + folder.getUrl());
  }

  // 3. Schema + seeds
  Crm.ensureSchema();
  seedConfigTab_();
  seedAgenciesFromSample_();
  applySheetUi();   // dropdowns + Readme tab
  seedSetupTab();   // no-code "answer the questions" onboarding form

  Logger.log([
    'Setup complete.',
    'Next steps:',
    ' - Open the "Setup" tab in the new sheet, answer the questions and paste your',
    '   API keys, then tick Save (or run applySetup). That sets your profile + keys.',
    ' - Create the master CV Google Doc (with a {{SUMMARY}} token) and paste its ID',
    '   into the Setup tab, or set MASTER_CV_DOC_ID in Script Properties.',
    ' - Populate the Contacts tab (type=agency) with recruitment agencies.',
    ' - Run dailySource()/scoreQueue() manually once to test, then installTriggers().'
  ].join('\n'));
}

function seedConfigTab_() {
  const sh = Crm.sheet_(Crm.TABS.CONFIG);
  if (sh.getLastRow() > 1) return;
  const rows = [
    ['SCORE_THRESHOLD', Config.defaults.SCORE_THRESHOLD],
    ['DAILY_SOURCE_CAP', Config.defaults.DAILY_SOURCE_CAP],
    ['DAILY_APPROVAL_N', Config.defaults.DAILY_APPROVAL_N],
    ['CHUNK_SIZE', Config.defaults.CHUNK_SIZE],
    ['AGENCY_DRAFTS_PER_RUN', Config.defaults.AGENCY_DRAFTS_PER_RUN]
  ];
  sh.getRange(2, 1, rows.length, 2).setValues(rows);
}

/**
 * Optional: paste a CSV of agencies into a Script Property named AGENCIES_CSV
 * (columns: name,email,focus) and this seeds the Contacts tab from it.
 */
function seedAgenciesFromSample_() {
  const csv = Config.get('AGENCIES_CSV');
  if (!csv) return;
  const contacts = Crm.readAll(Crm.TABS.CONTACTS);
  if (contacts.length > 0) return;
  const rows = Utilities.parseCsv(csv);
  rows.forEach(function (r, i) {
    if (i === 0 && String(r[0]).toLowerCase() === 'name') return; // header
    if (!r[0]) return;
    Crm.appendRow(Crm.TABS.CONTACTS, {
      id: 'agency_' + i, name: r[0], email: r[1] || '', type: 'agency',
      company: r[0], focus: r[2] || '', last_contacted: '', notes: ''
    });
  });
}


// ======================================================================
// Diagnostics.gs
// ======================================================================

/**
 * Diagnostics.gs - run diagnose() and read the Execution log.
 * Checks which Script Properties are set and live-tests Adzuna + Gemini + the sheet.
 */
function diagnose() {
  const out = [];
  const P = PropertiesService.getScriptProperties();
  const has = function (k) { const v = P.getProperty(k); return v ? ('SET (' + String(v).length + ' chars)') : 'NOT SET'; };

  out.push('=== Script Properties ===');
  ['GEMINI_API_KEY', 'GEMINI_MODEL', 'ADZUNA_APP_ID', 'ADZUNA_APP_KEY', 'ADZUNA_API_KEY',
    'RAPIDAPI_KEY', 'SHEET_ID', 'DRIVE_FOLDER_ID', 'MASTER_CV_DOC_ID', 'CANDIDATE_JSON'].forEach(function (k) {
    out.push('  ' + k + ': ' + has(k));
  });

  out.push('=== Adzuna live test ===');
  try {
    const appId = P.getProperty('ADZUNA_APP_ID');
    const appKey = P.getProperty('ADZUNA_APP_KEY') || P.getProperty('ADZUNA_API_KEY');
    if (!appId || !appKey) {
      out.push('  SKIP - app id and/or key missing (this is why dailySource added 0)');
    } else {
      const url = 'https://api.adzuna.com/v1/api/jobs/za/search/1?app_id=' + encodeURIComponent(appId) +
        '&app_key=' + encodeURIComponent(appKey) + '&results_per_page=3&what=' +
        encodeURIComponent('customer service') + '&sort_by=date&max_days_old=21&content-type=application/json';
      const res = UrlFetchApp.fetch(url, { muteHttpExceptions: true });
      out.push('  HTTP ' + res.getResponseCode());
      const body = res.getContentText();
      try {
        const d = JSON.parse(body);
        if (d.exception) out.push('  exception: ' + d.exception);
        else out.push('  count: ' + d.count + ', results returned: ' + (d.results ? d.results.length : 0));
      } catch (e) { out.push('  body: ' + body.slice(0, 200)); }
    }
  } catch (e) { out.push('  ERROR: ' + e); }

  out.push('=== JSearch live test ===');
  try {
    const key = P.getProperty('RAPIDAPI_KEY');
    if (!key) {
      out.push('  SKIP - RAPIDAPI_KEY missing (JSearch source disabled until set)');
    } else {
      const url = 'https://jsearch.p.rapidapi.com/search-v2?query=' +
        encodeURIComponent('customer service in South Africa') +
        '&country=za&date_posted=week';
      const res = UrlFetchApp.fetch(url, {
        method: 'get', muteHttpExceptions: true,
        headers: { 'X-RapidAPI-Key': key, 'X-RapidAPI-Host': 'jsearch.p.rapidapi.com' }
      });
      out.push('  HTTP ' + res.getResponseCode());
      const body = res.getContentText();
      if (res.getResponseCode() !== 200) {
        // 404/403 here is a RapidAPI subscription/key issue - the body says which.
        out.push('  body: ' + body.slice(0, 200));
      } else {
        try {
          const d = JSON.parse(body);
          const arr = Sources.pickJobs_(d);
          const n = arr.length;
          out.push('  results returned: ' + n + (n
            ? ('  sample link: ' + (arr[0].job_apply_link || '').slice(0, 80))
            : ('  top-level keys: ' + Object.keys(d).join(',') + '  body: ' + body.slice(0, 200))));
        } catch (e) { out.push('  body: ' + body.slice(0, 200)); }
      }
    }
  } catch (e) { out.push('  ERROR: ' + e); }

  out.push('=== Gemini live test ===');
  try {
    const r = Gemini.generate('Reply with exactly: ok', { maxOutputTokens: 10 });
    out.push('  reply: ' + String(r).trim().slice(0, 40));
  } catch (e) { out.push('  ERROR: ' + e); }

  out.push('=== Sheet ===');
  try {
    out.push('  Opportunities rows: ' + Crm.readAll(Crm.TABS.OPPORTUNITIES).length);
  } catch (e) { out.push('  ERROR: ' + e); }

  const report = out.join('\n');
  Logger.log(report);
  return report;
}

/**
 * One-off maintenance: follow every stored job link and retire the dead ones.
 * Opportunities -> status 'dead_link'; Approvals -> decision 'Skip - dead link'
 * (which also drops it from the morning digest, which only lists blank-decision rows).
 * Non-destructive - rows are kept for the record, just flagged.
 * Capped per run to stay under the 6-minute limit; re-run until it reports 0 remaining.
 */
function pruneDeadLinks() {
  Crm.ensureSchema();
  const MAX_CHECKS = 80;                          // lower cap: slow redirect-follows add up
  const deadline = Date.now() + 4.5 * 60 * 1000;  // stop before the 6-minute hard kill
  let budget = MAX_CHECKS;
  let oppDead = 0, oppChecked = 0, apprDead = 0, apprChecked = 0, capped = false;

  Crm.readAll(Crm.TABS.OPPORTUNITIES).forEach(function (o) {
    if (!o.url || o.status === 'dead_link') return;
    if (budget <= 0 || Date.now() > deadline) { capped = true; return; }
    budget--; oppChecked++;
    if (!Sources.linkAlive_(o.url)) {
      Crm.updateRow(Crm.TABS.OPPORTUNITIES, o._row, {
        status: 'dead_link',
        notes: String(o.notes || '') + ' [pruned: dead link]',
        updated_at: new Date()
      });
      oppDead++;
    }
  });

  Crm.readAll(Crm.TABS.APPROVALS).forEach(function (a) {
    if (!a.url || String(a.decision || '').trim()) return;   // leave already-decided rows alone
    if (budget <= 0 || Date.now() > deadline) { capped = true; return; }
    budget--; apprChecked++;
    if (!Sources.linkAlive_(a.url)) {
      Crm.updateRow(Crm.TABS.APPROVALS, a._row, {
        decision: 'Skip - dead link',
        edited_notes: String(a.edited_notes || '') + ' [pruned: dead link]'
      });
      apprDead++;
    }
  });

  const report = 'pruneDeadLinks: Opportunities ' + oppDead + '/' + oppChecked + ' dead; ' +
    'Approvals ' + apprDead + '/' + apprChecked + ' dead.' +
    (capped ? ' CAPPED (hit the ' + MAX_CHECKS + '-check or time budget) - re-run to continue.' : ' Done.');
  Logger.log(report);
  return report;
}


