#!/usr/bin/env bash
#
# bundle.sh - regenerate manual-install/Code.gs from src/*.gs.
#
# src/ is the source of truth. The manual (no-terminal) install path pastes the
# single bundled file, so run this whenever you change anything under src/:
#
#   bash tools/bundle.sh
#
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/manual-install/Code.gs"

# Load order is cosmetic (Apps Script shares one global scope across files), but
# keep dependencies-ish first for readability.
ORDER=(Config Gemini Prompts Crm Sources Match Tailor MasterCv Outreach Digest \
       InterviewPrep Report Loop Triggers SheetUi Onboarding Setup Diagnostics)

# Safety net: every src/*.gs must be listed in ORDER, or the bundle would silently
# drop it.
for f in "$ROOT"/src/*.gs; do
  n="$(basename "$f" .gs)"
  found=0
  for o in "${ORDER[@]}"; do [ "$o" = "$n" ] && found=1 && break; done
  [ "$found" -eq 1 ] || { echo "error: src/$n.gs is not listed in ORDER in tools/bundle.sh" >&2; exit 1; }
done

mkdir -p "$ROOT/manual-install"
{
  printf '/**\n'
  printf ' * Code.gs - GENERATED single-file bundle of all src/*.gs.\n'
  printf ' * For the no-terminal install: paste this whole file into one script file at\n'
  printf ' * script.google.com. src/ is the source of truth - regenerate with\n'
  printf ' * `bash tools/bundle.sh` after any change. Do not edit this file by hand.\n'
  printf ' */\n\n'
  for name in "${ORDER[@]}"; do
    f="$ROOT/src/$name.gs"
    [ -f "$f" ] || { echo "error: missing src/$name.gs" >&2; exit 1; }
    printf '// ======================================================================\n'
    printf '// %s.gs\n' "$name"
    printf '// ======================================================================\n\n'
    cat "$f"
    printf '\n\n'
  done
} > "$OUT"

echo "wrote $OUT ($(grep -c '' "$OUT") lines, ${#ORDER[@]} files)"
